### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by EthanZeigler** [berniegp/vue-unique-id#13]
Using this plugin with vue3 will cause an error indicating Vue.prototype is undefined. More information can be found [here](https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties).

**Comment by berniegp** [comment]
I don't currently use Vue3 and at first sight I don't see a good way to make this very small plugin support both Vue2 and Vue3 at the same time _without bloating it_ (the code itself and the repository).

If you or someone else has insight on this and/or the bandwidth to contribute a pull request, you are most welcome :)

**Comment by doutatsu** [comment]
Came here hoping for Vue 3 support 😢 Maybe `next` or `vue3` branch could added with basic support?

**Comment by romain130492** [comment]
well if it can helpfull I personally used the package [`uuid`](https://www.npmjs.com/package/uuid) with vue-3

* the only way to make it work was to create a JS file in utils with a method

* then I import that utility method to my vue component
example:

```js
// /utils/uuid.js
import { v4 as uuidv4 } from "uuid";

export function generateUUID() {
  return uuidv4();
}

```
```vue

<script>
  import { generateUUID } from "./../utils/uuid.js";
  export default {
  mounted() {
      console.log(generateUUID(), "UUID");
    },
}
</script>

```

**Comment by snoozbuster** [comment]
hey @berniegp. I think vue 3 support ought to be pretty straightforward, the only thing I see in the plugin which is not supported in Vue 3 is the use of `Vue.prototype`. To support Vue 3 I think we just need to add

```
const globalPrototype = Vue.version.slice(0, 2) === '3.' ? Vue.config.globalProperties : Vue.prototype
```

right before [these lines](https://github.com/berniegp/vue-unique-id/blob/master/src/plugin.js#L56-L57), and then use `globalPrototype` in those lines instead of `Vue.prototype`. Everything else could remain the same, and Vue 3 users would be able to call `createApp(...).use(VueUniqueId)` to install the plugin.

Let me know if you're still around to accept PRs for this package and I can do a quick test in one of my apps and then make the PR.

**Comment by berniegp** [comment]
Hi! Sorry for the slow reply. My GitHub notifications had suddenly stopped.

Yes I'm still glad to accept PRs

**Comment by berniegp** [comment]
Hi @snoozbuster! Sorry for the slow reply. My GitHub notifications had suddenly stopped and I didn't notice.

Yes I'm still glad to accept PRs

**Comment by snoozbuster** [comment]
@berniegp awesome! I’ll submit a PR later today with the tweaked code I’ve been using in my project.

**Comment by snoozbuster** [comment]
okay, sorry for the delay. didn't end up getting back to my laptop yesterday. I've opened a PR: https://github.com/berniegp/vue-unique-id/pull/14

**Comment by berniegp** [comment]
# Development of this plugin is discontinued. It still works perfectly well with Vue2, but I don't have time to port it to Vue3 and maintain it anymore.
This is a really small plugin so feel free to its code and add it directly to your project. Good luck!

There's also a fork that probably works with Vue3 here: https://github.com/snoozbuster/vue-unique-id
